medicine_tracker/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls')),
]

tracker/urls.py
from django.urls import path
from . import views

app_name = "tracker" 

# including urls patterns and their rout to views 
urlpatterns = [
    path("signup/",views.signup,name="signup"),
    path("login/",views.log_in,name="login"),
    path("logout/",views.log_out,name="logout"),
    path("index/",views.index,name="index"),
    path("add/",views.add,name="add"),


]

tracker/models.py
from django.db import models

# Creating models here.

class Medicine(models.Model):
    name = models.CharField(max_length=100)
    dosage = models.CharField(max_length=50)
    frequency = models.IntegerField()

    def __str__(self):
        return self.name
    

tracker/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

# Creating views here.

def signup(request):
    # creating new user object in User model in database
    if request.method=="POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        User.objects.create_user(username=username, email=email, password=password)
        return HttpResponseRedirect(reverse("tracker:login"))
    return render(request, "tracker\signup.html")

def log_in(request):
    # authenticating user credentials 
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            # rendirect to index view when logged in
            return HttpResponseRedirect(reverse("tracker:index"))
        else:
            error_msg = {"error" :  "Incorrect credentials! Try Again."}
            return render(request, "tracker\login.html",error_msg)
    return render(request, "tracker\login.html")

def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("tracker:login"))

def index(request):
    return render(request, "tracker/index.html")

def add(request):
    return render(request, "tracker/add.html")

tracker/templates/tracker/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add</title>
</head>
<body>
    
    <p>Add your medicines here</p>

</body>
</html>

tracker/templates/tracker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <p><h2>Welcome to medicine tracker. You can add your medicines, suppliments, ointmets to keep track of your medications.</h2></p>
    <br>
    <a href={% url "tracker:add" %}>Add Medicine</a>
    <br>
    <a href={% url "tracker:logout" %}>Logout</a>
    
    
</body>
</html>

tracker/templates/tracker/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    {% comment %} error message for wrong credentials {% endcomment %}
    {% if error %}
        <p>{{error}}</p>
    {% endif %}
    {% comment %} login form {% endcomment %}
    <form action={% url "tracker:login" %} method="POST">
        {% csrf_token %}
        <legend><h1>Login</h1></legend>
        <label for="user">Username<superscript>*</superscript> </label>
        <input type="text" name="username" id="user"><br>
        <label for="pass">Passsword<superscript>*</superscript> </label>
        <input type="password" name="password" id="pass">
        <input type="submit" name="Login">
    </form>
    {% comment %} url for signup {% endcomment %}
    <p>Don't have an account? <a href={% url "tracker:signup" %}>Signup</a></p>
</body>
</html>

tracker/templates/tracker/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
</head>

<body>
    <form action={% url "tracker:signup" %} method="POST">
        {% csrf_token %}
        {% comment %} signup form  {% endcomment %}
        <legend><h1>Signup</h1></legend>
        <label for="user">Username<superscript>*</superscript></label>
        <input type="text" name="username" id="user"><br>
        <label for="email">Email<superscript>*</superscript></label>
        <input type="text" name="email" id="email"><br>
        <label for="pass"> Passsword<superscript>*</superscript></label>
        <input type="password" name="password" id="pass">
        <input type="submit" name="Signup">
    </form>
    {% comment %} url for login  {% endcomment %}
    <p>Already have an account? <a href={%url "tracker:login"%}>Login</a></p>
</body>

</html>